// Copyright (c) 2023 Google LLC
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#pragma once

#include "core/defines.dl"
#include "core/value_analysis.dl"
#include "core/vreg_analysis.dl"
#include "core/control_flow.dl"
#include "core/operand.dl"
#include "core/operand_utils.dl"
#include "core/function.dl"
#include "core/block.dl"
#include "core/check.dl"

#ifdef DEBUG_VULN_BO_IN_ARRAY
#define OUTPUT(x) OUTPUT_IMPL(x)
#else
#define OUTPUT(x)
#endif


.decl bo_in_array(func: symbol, iid: instr_t, name: name_t, msg: symbol)
OUTPUT(bo_in_array)

bo_in_array(func, iid, name, msg) :-
  Function.get(fid, func, _),
  Block.get(fid, bid, bname),
  Instruction.GetElementPtr.addr_size(iid, bid, name, size),
  Instruction.GetElementPtr.index(iid, idx_op),
  (Operand.int(idx_op, idx);
   OperandUtil.name(idx_op, idx_vreg, _),
   Check.get_upperbound_limited_value(fid, bid, idx_vreg, idx)
  ),
  idx >= size,
  msg = cat("BUFFER OVERFLOW: block '", bname, "': possibly insufficient buffer size of ",
            name, "(", to_string(size), " elements). ",
            "Detected to big index access ", to_string(idx)).

