// Copyright (c) 2023 Google LLC
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#pragma once

#include "core/defines.dl"
#include "core/value_analysis.dl"
#include "core/vreg_analysis.dl"
#include "core/control_flow.dl"
#include "core/operand.dl"
#include "core/operand_utils.dl"
#include "core/function.dl"
#include "core/block.dl"
#include "core/check.dl"
#include "core/loop.dl"

#ifdef DEBUG_VULN_BO_IN_LOOP
#define VBL_OUTPUT(x) OUTPUT_IMPL(x)
#else
#define VBL_OUTPUT(x)
#endif


.decl bo_in_loop(func: symbol, iid: instr_t, level: symbol, msg: symbol)
VBL_OUTPUT(bo_in_loop)

bo_in_loop(func, iid, level, msg) :-
  Function.get(fid, func, _, _),
  Block.get(fid, bid, bname),

  Instruction.GetElementPtr.addr_size(iid, bid, name, size),

  Instruction.GetElementPtr.index(iid, idx_op),
  Operand.vreg(idx_op, idx_vreg, _),

  Loop.node(fid, loop_head, bid),
  Loop.condition_instr(fid, loop_head, cmp_iid),
  Check.check_boundary(fid, _, cmp_iid, pred, cmp_vreg, value_op, _, _),
  GET_INT_FROM_OP(fid, value_op, value),
  cmp_vreg = idx_vreg,
  (
   SMALLER_COND(pred), iter_value = value - 1;
   SMALLER_EQUAL_COND(pred), iter_value = value
  ),
  size <= iter_value,
  level = "Vulnerability",
  msg = cat("BUFFER OVERFLOW: block '", bname,
            "': Array access withing a loop with the loop variable ",
            name, "(", to_string(size), " elements) is out of bounds for i = ",
            to_string(iter_value)).

