//define all functors
.functor get_before_underscore(symbol):symbol
.functor get_behind_underscore(symbol):symbol
.functor get_before_seperator(symbol):number 
.functor get_before_xseperator(symbol):number 
.functor get_behind_seperator(symbol):symbol
.functor get_behind_xseperator(symbol):symbol
.functor get_num_seperators(symbol):number 
.functor get_num_xseperators(symbol):number 
.functor remove_one_zero(symbol):symbol