//types
#include "types.dl"

//Constants and Macros
#define MAXINT 2147483647
#define MAXDEEP 100

//framework
#include "functors.dl"
#include "config.dl"
#include "util.dl"
#include "test.dl"
#include "call_graph.dl"
#include "instructions.dl"
#include "operands.dl"
#include "control_flow.dl"
#include "loops.dl"
#include "memlocation.dl"
#include "memlocation_structs.dl"
#include "memlocation_arrays.dl"

//rules & analysis 
#include "alias.dl"
#include "points_to.dl"
#include "taint.dl"
#include "memops.dl"
#include "value_analysis.dl"


//vulnerable detection
#include "vulnerabilities.dl"