//atoi family used with userinput
.decl is_vulnerable_atoi_call_instruction(instructionid: _instructionid, message: symbol)
is_vulnerable_atoi_call_instruction(IID, MESSAGE) :- 
is_atoi_family_call_instruction(IID),
block(FID, BID, _), instruction(BID, IID, _, _),
get_first_operand(IID, SRC),
is_vreg(SRC),
is_memloc_with_userinput(FID, SRC, _),
MESSAGE = "atoi-family call with userinput: integer overflow/undefined behavior possible."
.

