//all integer overflows
.decl integer_overflow(instructionid: _instructionid, level: symbol, message: symbol)
integer_overflow(IID, LEVEL, MESSAGE) :- is_vulnerable_atoi_family_instruction(IID, LEVEL, MESSAGE).

//atoi family used with userinput
.decl is_vulnerable_atoi_family_instruction(instructionid: _instructionid, level:symbol, message: symbol)
is_vulnerable_atoi_family_instruction(IID, LEVEL, MESSAGE) :- 
is_atoi_family_call_instruction(IID),
block(FID, BID, _), instruction(BID, IID, _, _),
get_first_operand(IID, SRC),
is_vreg(SRC),
is_memloc_with_userinput(FID, SRC),
MESSAGE = "atoi-family call with userinput: integer overflow/undefined behavior possible.",
LEVEL = "Vulnerability"
.

