// Copyright (c) 2023 Google LLC
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#include "core/defines.dl"
#include "core/value_analysis.dl"
#include "core/vreg_analysis.dl"
#include "core/control_flow.dl"
#include "core/operand.dl"
#include "core/operand_utils.dl"
#include "core/function.dl"
#include "core/block.dl"
#include "core/check.dl"
#include "core/results.dl"

#ifdef DEBUG_VULN_NULL_FREE
#define VNF_OUTPUT(x) OUTPUT_IMPL(x)
#else
#define VNF_OUTPUT(x)
#endif


.decl null_free(func: symbol, iid: instr_t, level: symbol, msg: symbol, line: symbol)
VNF_OUTPUT(null_free)

null_free(func, iid, level, msg, line) :-
  Function.get(fid, func, _, _, line),
  Block.get(fid, bid, bname),
  Instruction.Call.global_func(iid, bid, _, fname, _),
  fname = "%free",
  Instruction.Call.ith_operand(iid, 0, op),
  OperandUtil.name(op, vreg, _),
  InstructionAnalysis.is_instruction_before(iid, iid_null),
  !Check.check_null(fid, bid, vreg),
  VRegValueAnalysis.is_null(fid, iid_null, vreg, _),
  level = "Vulnerability",
  msg = cat("NULL Free: VREG:", vreg, "(block ", bname,
            " / iid ", to_string(iid), ") attempt to free NULL pointer!").


REPORT_RESULTS(null_free).