//all out-of-bounds-reads
.decl out_of_bounds_read(instructionid: _instructionid, level: symbol, message: symbol)
out_of_bounds_read(IID, LEVEL, MESSAGE) :- is_strncpy_out_of_bounds_read(IID, LEVEL, MESSAGE).

//strncpy vulnerable to out of bounds read
.decl is_strncpy_out_of_bounds_read(instructionid: _instructionid, level: symbol, message: symbol)
is_strncpy_out_of_bounds_read(IID, LEVEL, MESSAGE) :- 
is_strncpy_call_instruction(IID),
block(FID, BID, _), instruction(BID, IID, _, _),
get_first_operand(IID, DEST), get_second_operand(IID, SRC), get_third_operand(IID, N), 
get_int_by_vreg(COPY_SIZE, FID, N),
get_buffsize_by_vreg(DEST_SIZE, FID, DEST), 
get_buffsize_by_vreg(SRC_SIZE, FID, SRC), 
DEST_SIZE = COPY_SIZE,
LEVEL = "Vulnerability",
MESSAGE = "strncpy: out of bounds read.",
SRC_SIZE >= COPY_SIZE.